### ISSUE TITLE
build failed on ubuntu 10.04

### ISSUE THREAD

**Issue by vsespb** [rafl/term-readline#1]
ubuntu 10.04 64bit, perl 5.10.1

with segfault btw

```
Test Summary Report
-------------------
t/AETk.t              (Wstat: 11 Tests: 3 Failed: 0)
  Non-zero wait status: 11
Files=5, Tests=24,  0 wallclock secs ( 0.00 usr  0.03 sys +  0.13 cusr  0.02 csys =  0.18 CPU)
Result: FAIL
Failed 1/5 test programs. 0/24 subtests failed.
make: *** [test_dynamic] Error 255
```

```
# perl AETk.t
1..3
ok 1 - Created object
ok 2 - Correct type
Do not press enter>ok 3 - Event loop called
Segmentation fault
```

**Comment by rafl** [comment]
I can't reproduce this failure. Could you provide a backtrace, preferably with debugging symbols, for the segfault, please? You might find the Devel::bt module from CPAN useful in doing so.

**Comment by vsespb** [comment]
Indeed, not reproducable under perlbrew's perl

Reproducable under vendor perl:

```
# perl -V
Summary of my perl5 (revision 5 version 10 subversion 1) configuration:

  Platform:
    osname=linux, osvers=2.6.42-37-generic, archname=x86_64-linux-gnu-thread-multi
    uname='linux batsu 2.6.42-37-generic #58-ubuntu smp thu jan 24 15:28:10 utc 2013 x86_64 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=x86_64-linux-gnu -Dprefix=/usr -Dprivlib=/usr/share/perl/5.10 -Darchlib=/usr/lib/perl/5.10 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.10.1 -Dsitearch=/usr/local/lib/perl/5.10.1 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Ud_ualarm -Uusesfio -Uusenm -DDEBUGGING=-g -Doptimize=-O2 -Duseshrplib -Dlibperl=libperl.so.5.10.1 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.4.3', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.11.1.so, so=so, useshrplib=true, libperl=libperl.so.5.10.1
    gnulibc_version='2.11.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options: MULTIPLICITY PERL_DONT_CREATE_GVSV
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_PERLIO USE_REENTRANT_API
  Built under linux
  Compiled at Mar 18 2013 18:34:04
  @INC:
    /etc/perl
    /usr/local/lib/perl/5.10.1
    /usr/local/share/perl/5.10.1
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.10
    /usr/share/perl/5.10
    /usr/local/lib/site_perl
    .


```

(i.e. either there are specific patches or specific build options, I did not try same arch/options in perlbrew)

stacktrace:

```
#  perl -d:bt t/AETk.t
1..3
ok 1 - Created object
ok 2 - Correct type
Do not press enter>ok 3 - Event loop called
#0  0x00007f3263bd644e in __libc_waitpid (pid=<value optimized out>, stat_loc=0x7fff684a97bc, options=<value optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:32
#1  0x00007f3263403cf8 in backtrace (sig=<value optimized out>) at bt.xs:183
#2  signal_handler (sig=<value optimized out>) at bt.xs:190
#3  <signal handler called>
#4  __strlen_sse42 () at ../sysdeps/x86_64/multiarch/strlen.S:54
#5  0x00007f326437df56 in Perl_is_utf8_string (my_perl=<value optimized out>, s=0x0, len=0) at utf8.c:285
#6  0x00007f3262b2f5a9 in Tcl_GetStringFromObj () from /usr/lib/perl5/auto/Tk/Tk.so
#7  0x00007f3262b2fcd1 in ?? () from /usr/lib/perl5/auto/Tk/Tk.so
#8  0x00007f326430a4e5 in Perl_mg_get (my_perl=0x614010, sv=0xddc8b0) at mg.c:221
#9  0x00007f3264326215 in Perl_sv_2pv_flags (my_perl=0x614010, sv=0x0, lp=0x7fff684a9fa0, flags=<value optimized out>) at sv.c:2745
#10 0x00007f3264314765 in S_method_common (my_perl=0x614010, meth=0xddd0a8, hashp=0x7fff684a9ffc) at pp_hot.c:3057
#11 0x00007f3264314b9e in Perl_pp_method_named (my_perl=0x614010) at pp_hot.c:3027
#12 0x00007f3264314346 in Perl_runops_standard (my_perl=0x614010) at run.c:40
#13 0x00007f32642bb8cf in Perl_call_sv (my_perl=<value optimized out>, sv=0xddceb0, flags=150) at perl.c:2717
#14 0x00007f32643286e6 in Perl_sv_clear (my_perl=0x614010, sv=0xdfa7e8) at sv.c:5432
#15 0x00007f3264328ee2 in Perl_sv_free2 (my_perl=0x614010, sv=0xdfa7e8) at sv.c:5693
#16 0x00007f326431de32 in S_visit (my_perl=0x614010, f=0x7f32643293b0 <do_clean_objs>, flags=2048, mask=2048) at sv.c:441
#17 0x00007f326431de91 in Perl_sv_clean_objs (my_perl=0x0) at sv.c:549
#18 0x00007f32642bdbe9 in perl_destruct (my_perl=<value optimized out>) at perl.c:833
#19 0x0000000000400d1c in main (argc=3, argv=0x7fff684aa4f8, env=0x7fff684aa518) at perlmain.c:119
Aborted
```

**Comment by vsespb** [comment]
Note, that when I reported the bug, 10.04 was supported distribution, now it's unsupported (end of life).
however I think Ubuntu Server 10.04 is still supported (but I did not test on it)
